# SERVER CONFIGURATION
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# SPRING CONFIGURATION
spring:
  application:
    name: movie-booking

    # DATABASE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booking
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/HIBERNATE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

  #Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: dohoan25112004@gmail.com
    password: dxbu jqon lyrt tckw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # JACKSON CONFIGURATION
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null

  # MULTIPART FILE UPLOAD
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


# JWT CONFIGURATION
jwt:
  expiryMinutes: 5
  expiryDay: 14
  accessKey: p1zs6HE4bebUL6aVjJhSEtj/Bp4rhQPK3vUR2gpcA06muNhYO77Z9kzb3U5sDXBkdpEZwECJfm0tNuDRiVu29g==


# LOGGING CONFIGURATION
logging:
  level:
    root: INFO
    com.moviebooking: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

  logback:
    rollingpolicy:
      clean-history-on-start: true


# MANAGEMENT & ACTUATOR (Optional)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized